#!/usr/bin/env bash

fzf_ollama_models() {
	running=$(ollama ps | awk 'NR > 1 {print $1}' | sort)
	models=$(ollama ls | awk 'NR > 1 {print $1}' | sort)

	ollama ls | awk 'NR > 1 {print $1}' |
		fzf \
			--prompt="Choose model: " \
			--preview='echo "=== Model Info ==="; ollama show $(echo {} | awk "{print \$1}"); echo \${running}' \
			--preview-window=right:70%

	# ollama ls | awk 'NR > 1 {print $1}' |
	# 	fzf --prompt="Choose model: " \
	# 		--preview='echo "=== Model Info ==="; ollama show $(echo {} | awk "{print \$1}")' \
	# 		--preview-window=right:70%
}

fzf_ollama_action() {
	echo -e "run\nstop\nrm\nshow\npull" | fzf --prompt="Choose action: "
}

model=$(fzf_ollama_models)
[[ -z "$model" ]] && echo "❌ No model selected." && exit 1

action=$(fzf_ollama_action)
[[ -z "$action" ]] && echo "❌ No action selected." && exit 1

case "$action" in
run)
	echo "ollama run $model"
	echo "🚀 Running model: $model"
	ollama run "$model"
	;;
show)
	echo "ollama show $model"
	echo "🚀 Model Info: $model"
	ollama show "$model"
	;;
pull)
	echo "ollama pull $model"
	echo "🚀 Pulling Model: $model"
	ollama pull "$model"
	;;
stop)
	echo "ollama stop $model"
	echo "⏹️ Stopping model: $model"
	ollama stop "$model"
	;;
rm)
	echo "ollama rm $model"
	echo "⚠️ You are about to delete model: $model"
	read -p "Are you sure? (y/N): " confirm
	if [[ "$confirm" =~ ^[Yy]$ ]]; then
		echo "🗑️ Removing model: $model"
		ollama rm "$model"
	else
		echo "❎ Delete canceled."
	fi
	;;
*)
	echo "❓ Unknown action: $action"
	;;
esac
